<?php

namespace Miky\Bundle\NewsletterBundle\Repository;

/**
 * NewsletterGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
